server:
  port: 8081
zuul:
  routes:
    serviceSimple:
      path: /ass/**
      url: http://localhost:3000/headers
  ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      serviceSimple:
      - limit: 5
        refresh-interval: 60
        type:
        - origin
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;Mode=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    continue-on-error: false
    initialization-mode: always